// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLdc_dbLXMMWuboth1QbktwoY7ls4W-0s',
    appId: '1:640227440909:web:b2fc86b7b2a61afd109844',
    messagingSenderId: '640227440909',
    projectId: 'travel-planning-app-651bc',
    authDomain: 'travel-planning-app-651bc.firebaseapp.com',
    storageBucket: 'travel-planning-app-651bc.appspot.com',
    measurementId: 'G-N1RHZY50N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaoPJzwxFFDfyvj9lKQ3Fa80JpBCq5DI',
    appId: '1:640227440909:android:5cb6868670cf6584109844',
    messagingSenderId: '640227440909',
    projectId: 'travel-planning-app-651bc',
    storageBucket: 'travel-planning-app-651bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCui1MLuoeU69wok6Zj4zAMaqNWj0bgpLk',
    appId: '1:640227440909:ios:11ae4ee55ced0561109844',
    messagingSenderId: '640227440909',
    projectId: 'travel-planning-app-651bc',
    storageBucket: 'travel-planning-app-651bc.appspot.com',
    iosBundleId: 'com.example.travelPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCui1MLuoeU69wok6Zj4zAMaqNWj0bgpLk',
    appId: '1:640227440909:ios:6d51ab4f15e39740109844',
    messagingSenderId: '640227440909',
    projectId: 'travel-planning-app-651bc',
    storageBucket: 'travel-planning-app-651bc.appspot.com',
    iosBundleId: 'com.example.travelPlanningApp.RunnerTests',
  );
}
